composer.json, src/Statistics/ComponentStatistics.php, tests/Statistics/ComponentStatisticsTest.php, tests/Stubs/Controllers/ProjectsController.php, tests/Stubs/Controllers/UsersController.php
This PR adds support of "Lines of Code" and "Logical Lines of Code" by using [phploc](https://github.com/sebastianbergmann/phploc).
refs #4
=> Add Support for Lines of Code

.travis.yml, composer.json, src/ClassFinder.php, src/Services/StatisticsListService.php
=> Add Support for PHP 7.0

src/Analyzers/ClassMethodsAnalyzer.php
This PR refactors `ClassMethodsAnalyzer::getTraitMethods()` method, making it use Laravel's collections.
=> Refactor method

src/Component.php, src/ComponentSort.php, tests/ComponentTest.php, tests/Statistics/ComponentStatisticsTest.php, tests/Statistics/ProjectStatisticsTest.php
This PR refactors ComponentSort to a single collection pipeline. It also refactors the Component class to set its attributes through constructor instead of setters. 
🌵
=> Refactor ComponentSort and Component

.travis.yml
This command is run automatically by Travis
=> do not update composer

src/Commands/StatsListCommand.php
This cleans up the command class.
=> use method injection

src/ClassFinder.php
There is no need to check for `Illuminate` and `Symfony` specifically as there is `isVendorProvided` check at the end of the pipeline.
Also, `isNative` check takes care of `stdClass`, `Exception` etc.
=> clean up method

src/Services/StatisticsListService.php, src/Statistics/ProjectStatistics.php, tests/Statistics/ProjectStatisticsTest.php
This cleans up the code a bit and is a bit more "OOP".
=> Pass components as argument to constructor

src/ReflectionClass.php, src/Statistics/ClassStatistics.php, src/Statistics/ComponentStatistics.php, tests/ReflectionClassTest.php
This cleans up the code quite a bit and makes for a nicer API.
=> Make ReflectionClass extend native ReflectionClass

src/StatsServiceProvider.php
=> Remove Container Binding

src/ClassFinder.php
How about changing the method visibility from public to protected if it is not expected to be called from other classes?
=> Modify method visibility

src/Classifiers/Classifier.php, src/ComponentSort.php, src/ReflectionClass.php, src/Services/StatisticsListService.php, tests/ClassifierTest.php, tests/Commands/StatsListCommandTest.php, tests/ComponentSortTest.php, tests/ReflectionClassTest.php
As discussed in #73.
I will propose a refactor of the `Classifier` in another PR, once this is merged.
This closes #73.
=> introduce 'Others' category

README.md, config/stats.php, src/Classifiers/Classifier.php, src/Classifiers/PhpUnitClassifier.php, tests/ClassifierTest.php, tests/Stubs/Tests/ExampleTest.php
Hello @stefanzweifel
This is a PR for issue #80 👍 
Thanks.
=> PHPUnit Tests Classifier

composer.json, src/Classifiers/BrowserKitTestClassifier.php, src/Classifiers/Classifier.php, tests/ClassifierTest.php, tests/Stubs/Tests/DemoBrowserKit.php
Detects Laravel BrowserKit Tests
Closes #16
=> Add BrowserKit Tests Classifier

src/Formatters/TableOutput.php, src/Statistics/CodeTestRatio.php, tests/Statistics/CodeTestRatioTest.php
This PR adds a new Metric to the command: Code to Test Ratio (like in `rake stats`).
#21
=> Feature: Code to Test Ratio

README.md, src/ComponentFinder.php, src/Formatters/JsonOutput.php, src/Statistics/CodeTestRatio.php, src/Statistics/JsonBuilder.php, src/StatsListCommand.php, tests/Commands/StatsListCommandTest.php, tests/Statistics/CodeTestRatioTest.php, tests/Statistics/JsonBuilderTest.php
This PR adds a new output format for the project statistics.
**Still a work in progress**
=> Feature: Json Output

src/Classifier.php, src/Formatters/TableOutput.php, src/Statistics/JsonBuilder.php, src/Statistics/NumberOfRoutes.php, tests/Statistics/NumberOfRoutesTest.php
Fixes Lumen compatibility issues raised in #138.
=> Restore Lumen compatibility

src/Classifiers/MiddlewareClassifier.php, tests/ComponentFinderTest.php, tests/Stubs/HttpKernel.php, tests/Stubs/Middlewares/RouteMiddleware.php
Include Route Middlewares when retrieving the Middlewares (getMiddlewares)
=> Include Route Middlewares

composer.json, tests/Stubs/Events/DemoEvent.php
Update Constraints in composer.json to support Laravel 6.0.
=> Add Support for Laravel 6.0

.travis.yml, composer.json
Just to make sure everything works as expected.
=> Test Package against Laravel 6.0 on Travis CI

src/Classifiers/Nova/DashboardClassifier.php, test-stubs-nova/Dashboards/Dashboard.php, tests/Classifiers/Nova/DashboardClassifierTest.php, tests/Stubs/Nova/DemoDashboard.php
I have added the Nova Dashboard Classifier and tests as mentioned in #154
=> Add DashboardClassifier

.gitattributes, .github/workflows/format_php.yml, .gitignore, .php_cs, composer.json, src/Classifiers/PolicyClassifier.php, tests/ReflectionClassTest.php
This PR adds php-cs-fixer as a dev dependency, a php-cs configuration file and a GitHub Actions Workflow.
The GitHub Actions workflow is run on pull-requests and executes php-cs-fixer and commits changed files back to the repository.
=> Add php-cs-fixer and GitHub Actions Workflow

src/Classifiers/BladeComponentClassifier.php, tests/Classifiers/BladeComponentClassifierTest.php, tests/Stubs/BladeComponents/StubBladeComponent.php
=> Add BladeComponent Classifier

.github/workflows/tests-l7.yml, .github/workflows/tests.yml
This PR prepares the package to support PHP 8.1.
=> Add Support for PHP 8.1

README.md, composer.json, src/Classifier.php, src/Classifiers/LivewireComponentClassifier.php, tests/Classifiers/LivewireComponentClassifierTest.php, tests/LivewireComponentClassifierTest.php, tests/Stubs/LivewireComponents/StubLivewireComponent.php
Adds a Livewire Component Classifier to show Livewire Components in stats output.
=> Livewire component classifier

.github/workflows/tests.yml, composer.json, src/Classifiers/EventListenerClassifier.php, src/Classifiers/ObserverClassifier.php
This PR adds support for Laravel 9.
=> Add Support for Laravel 9

composer.json
=> Add Support for PhpUnit 10
