- .travis.yml
- composer.json
- src/Analyzers/ClassMethodsAnalyzer.php
- tests/Analyzers/ClassMethodsAnalyzerTest.php
This PR adds a new `getMethodsWithoutTraitMethods`  on the `ClassMethodsAnalyzer` class. 
The new method will first collect all method names declared on all the traits used by the class and will then return the diff between the previously collected method names and the trait-method names.
> Ignore Methods declared on any trait

- src/ClassFinder.php
- src/ReflectionClass.php
- tests/ClassFinderTest.php
This is an initial PR to look at the best way to ignore native (PHP provided) classes as well as vendor provided classes.
> Don't count native and vendor classes

- .gitignore
- .travis.yml
- README.md
- composer.json
- phpunit.xml
This might seem controversial at first but hear me out:
1. It produces incorrect feedback (https://github.com/stefanzweifel/laravel-stats/pull/31#issuecomment-336170248)
2. **It's SLOW**. It takes up to 40 seconds to run tests on Travis when generating code coverage, compared to 300ms (on my machine)
3. It has outdated dependencies, causing composer to complain: `guzzle/guzzle`
4. Code coverage can still be generated locally by running: `phpunit --coverage-html=./coverage` (I'd suggest creating a composer script for this)
5. Code coverage is a nice metrics to find out what parts of the project need more focus. However, this does not need to be checked/generated every time there is a change. Code coverage doesn't tell you wether your system works. It only points out sections of the system …
> Suggestion: Remove coveralls

- config/stats.php
- src/ClassFinder.php
- tests/ClassFinderTest.php
- tests/Stubs/ExcludedFile.php
- tests/Stubs/Views/index.blade.php
- tests/Stubs/Views/index.html
- tests/Stubs/Views/index.twig.php
This PR introduces a new way to configure this package.
Config file now looks accordingly:
```php
return [
/**
* List of folders to be analyzed.
*/
'paths' => [
base_path('app'),
],
/**
* List of files/folders to be excluded from analysis.
*/
'exclude' => [
// base_path('app/helpers.php'),
// base_path('app/Services'),
],
];
```
**stats.paths** option allows users to include any number of folders. By default, `paths` includes only `/app` folder, which is most common.
**stats.ecxlude** option allows users to specify files or folder that should be excluded. By default, `exclude` is empty.
Please note, all paths specified in the config file must be absolute paths (using path helpers). I have included couple of examples.
> Refactor config (base_path and ignores)

- config/stats.php
- src/ClassFinder.php
While testing the command in real-life apps after merging #42 the command has thrown some exceptions (While requiring Model Factories for example).
I've wrapped the `require_once` statement in a Try/Catch block so the exceptions get caught.
I've also added the `database`-folder to the default array of paths to look for Laravel Components (Otherwise Migrations and Seeders would not show up in the stats-table).
> Wrap the require statement in Try/Catch Block

- src/ClassFinder.php
- src/Commands/StatsListCommand.php
- src/Component.php
- src/ReflectionClass.php
- src/Services/StatisticsListService.php
- src/Statistics/ComponentStatistics.php
- src/Statistics/ProjectStatistics.php
Updated the PHPDoc to fit the latest code.
I used just class name if the class importing is declared before class declaration,
if not used fully qualified class name.
> Clean up the PHPDoc

- src/StatsListCommand.php
- src/StatsServiceProvider.php
This PR moves the `StatsListCommand` class out of the `Commands` folder as there will never be more than one command.
---
#100 yay 🎉
> Move Command class

- src/Formatters/TableOutput.php
- src/Statistics/ProjectStatistics.php
- tests/Statistics/ProjectStatisticsTest.php
- tests/Stubs/ExcludedFile.php
This PR cleans up `ProjectStatistics` API. Passing result from `$stats->generate()` to `$stats->getTotalRow()` feels really weird. It suggests that we are missing an abstraction of "ComponentAnalyser". We can take a look into that once the API stabilizes.
> Refactor ProjectStatistics API

- src/StatsListCommand.php
As you can see in the screenshot below, the descriptions of the built-in Artisan commands use sentence case. However, `laravel-stats` uses title case for its description, thus being inconsistent with the other commands.
This pull requests simply proposes to fix that :)
> Make casing of command description consistent with built-in commands

- src/Classifiers/Classifier.php
- src/Classifiers/EventListenerClassifier.php
- tests/ClassifierTest.php
- tests/Stubs/EventListeners/DemoEventListener.php
- tests/Stubs/ServiceProviders/EventServiceProvider.php
- tests/TestCase.php
This PR adds a new `EventListenerClassifier`. The Classifier checks the `$listen` property on the `EventServiceProvider` and will only return `true`if the Listener has been registered.
#75
> New Classifier: Event Listener

- config/stats.php
- src/ComponentFinder.php
- tests/Commands/StatsListCommandTest.php
- tests/ComponentFinderTest.php
This PR adds a new config: `ignored_namespaces`.
If the newly added `RejectInternalClasses`-strategy is used, the packages own Service Provider and Command and all default Laravel Components under the `Illuminate` namespace count toward the project statistics.
This is obviously not a good thing. This new config rejects all classes which belong to a certain namespace (We use the `starts_with`-string helper here).
> New Config: Ignore Namespaces

- README.md
- config/stats.php
- src/Classifier.php
- src/Classifiers/BrowserKitTestClassifier.php
- src/Classifiers/Classifier.php
- src/Classifiers/CommandClassifier.php
- src/Classifiers/ControllerClassifier.php
- src/Classifiers/DuskClassifier.php
- src/Classifiers/EventClassifier.php
- src/Classifiers/EventListenerClassifier.php
- src/Classifiers/JobClassifier.php
- src/Classifiers/MailClassifier.php
- src/Classifiers/MiddlewareClassifier.php
- src/Classifiers/MigrationClassifier.php
- src/Classifiers/ModelClassifier.php
- src/Classifiers/NotificationClassifier.php
- src/Classifiers/PhpUnitClassifier.php
- src/Classifiers/PolicyClassifier.php
- src/Classifiers/RequestClassifier.php
- src/Classifiers/ResourceClassifier.php
- src/Classifiers/RuleClassifier.php
- src/Classifiers/SeederClassifier.php
- src/Classifiers/ServiceProviderClassifier.php
- src/ComponentFinder.php
- src/Contracts/Classifier.php
- tests/ClassifierTest.php
- tests/Stubs/MyCustomComponentClass.php
- tests/Stubs/MyCustomComponentClassifier.php
**Work in Progress**
This PR adds a new feature to `laravel-stats`. It will allow users to define their own classifiers in the `stats.php` config file.
Custom Component Classifiers will have to implement the `Classifier` contract.
> Feature: Custom Components

- composer.json
This PR adds support for Laravel 5.6.
I will merge and release a new version after Laravel 5.6 has been officially released on February 7th 2018.
refs #118
> Change Version Contraints to Support Laravel 5.6

- src/Classifier.php
In a project of mine, certain Service Providers have been disabled (eg. the AuthServiceProvider). When the `stats` command is run it fails, as some classes and helpers have not been created during the boot of the framework.
Luckily, Laravel comes with a handy [`rescue`](https://laravel.com/docs/5.6/helpers#method-rescue) function. When the `satisfies`-method on a `Classifiers` throws an exception, the exception is catched in the rescue function and the `$satisfies` value falls back to `false`.
> Wrap satisfies in rescue funcion callback

- CHANGELOG.md
- composer.json
This PR adds support for Laravel 5.7 and also updates other Laravel related dependencies.
Closes #123
> Add Laravel 5.7 support

- .travis.yml
- composer.json
- tests/Commands/StatsListCommandTest.php
Update the `.travis.yml` file to test the package against supported Laravel and PHP versions.
Inspired by the [this](https://blog.tjmiller.me/verifying-laravel-version-compatibility) blog post by [TJ Miller](https://twitter.com/SIXLIV3).
> Test package against multiple Laravel and PHP Versions

- README.md
- src/Classifier.php
- src/Classifiers/Nova/Action.php
- src/Classifiers/Nova/Filter.php
- src/Classifiers/Nova/Lens.php
- src/Classifiers/Nova/Resource.php
As mentioned in #124, I would like to add the 4 main Nova components to the stats output.
As Nova is a payed package, I didn't add the real Nova classes to the package and I also didn't write tests to cover those new classifiers.
I plan to rewrite some of the core parts of the package over the coming weeks, to make testing the internals a bit easier and will also then add tests for the Nova classifiers.
> Add Laravel Nova Classifiers

- README.md
- config/stats.php
- src/ComponentFinder.php
- src/ReflectionClass.php
- src/Statistics/CodeTestRatio.php
- src/Statistics/ProjectStatistics.php
- tests/Commands/StatsListCommandTest.php
String and Array helpers are being deprecated in Laravel 5.8 ([Laravel News article](https://laravel-news.com/laravel-5-8-deprecates-string-and-array-helpers)).
This PR replaces the calls to the helpers with calls to the `Str`-class.
> Refactor: Use Str-class instead of String Helpers

- src/Classifiers/ControllerClassifier.php
An exception thrown from laravel's getController stops the collection of controller stats. This let's the stats collection process continue.
> Prevent Laravel's exception throwing

- .travis.yml
- composer.json
Looks like the package is broken on PHP 7.3.
> ErrorException: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? - [Travis CI](https://travis-ci.org/stefanzweifel/laravel-stats/jobs/467445599#L554)
This is caused by the [Analyser](https://github.com/sebastianbergmann/phploc/blob/1799bbc0e1e25d4e27ead845b640e8a7e480558c/src/Analyser.php#L92) class in phploc.
As this is a dependency of this package, someone would have to open a PR similar to [this one from the PHP_CodeSniffer project](https://github.com/squizlabs/PHP_CodeSniffer/pull/2086).
> Test against PHP 7.3

- src/Formatters/TableOutput.php
- src/Statistics/JsonBuilder.php
- src/Statistics/NumberOfRoutes.php
- tests/Commands/StatsListCommandTest.php
- tests/Statistics/NumberOfRoutesTest.php
One metric currently missing from `stats` is the total number of registered routes in an application. Laravel comes with a `artisan route:list` command out of the box, but this command doesn't count the routes.
This PR calculates the number of routes and displays them in the "meta-data" row at the bottom of the table.
> Display Total Number of Routes

- src/Classifier.php
- src/Classifiers/BrowserKitTestClassifier.php
- src/Classifiers/CommandClassifier.php
- src/Classifiers/ControllerClassifier.php
- src/Classifiers/DuskClassifier.php
- src/Classifiers/EventClassifier.php
- src/Classifiers/EventListenerClassifier.php
- src/Classifiers/JobClassifier.php
- src/Classifiers/MailClassifier.php
- src/Classifiers/MiddlewareClassifier.php
- src/Classifiers/MigrationClassifier.php
- src/Classifiers/ModelClassifier.php
- src/Classifiers/NotificationClassifier.php
- src/Classifiers/Nova/Action.php
- src/Classifiers/Nova/Filter.php
- src/Classifiers/Nova/Lens.php
- src/Classifiers/Nova/Resource.php
- src/Classifiers/PhpUnitClassifier.php
- src/Classifiers/PolicyClassifier.php
- src/Classifiers/RequestClassifier.php
- src/Classifiers/ResourceClassifier.php
- src/Classifiers/RuleClassifier.php
- src/Classifiers/SeederClassifier.php
- src/Classifiers/ServiceProviderClassifier.php
- src/Contracts/Classifier.php
- tests/Stubs/Events/DemoEvent.php
- tests/Stubs/MyCustomComponentClassifier.php
I'm currently scimming through the code, before I start working on version 2.0 off this package and I recognized this inconsistency in method names in the `Classifier`-contract. 
For 2.0, I would like to move away from the `get`-/`set`-prefixes.
**This is a breaking change which will be documented in the 1.0 > 2.0 upgrade Guide.**
> [v2] Rename getName() to name() in Classifier Contract

- src/Formatters/TableOutput.php
- src/Statistics/CodeTestRatio.php
- src/Statistics/ComponentStatistics.php
- src/Statistics/JsonBuilder.php
- src/Statistics/ProjectStatistics.php
- tests/Statistics/ComponentStatisticsTest.php
- tests/Statistics/ProjectStatisticsTest.php
Since the beginning the package showed the number of "Lines of Code" as "Lines" and the number of "Logical Lines of Code" as "LoC" **(not as "LLoC")**.
However, there's an important distinction between "Lines of Code" and "Logical Lines of Code" (LLoC) (See [Wikipedia](https://en.wikipedia.org/wiki/Source_lines_of_code)).
To make things clearer of what is what, the package now uses the the correct term "LLoC".
**This is a breaking change whill has to be documented in the ugprade guide.**
> [v2] Rename "LoC" to "LLoC"

- .travis.yml
- composer.json
- src/Console/StatsListCommand.php
- tests/Console/StatsListCommandTest.php
This PR drops support for Laravel 5.6, 5.7 and PHP 7.1.
I've decided to drop support for these versions, as they no longer receive fixes or security fixes or will reach their end of life in the upcoming **days** or weeks.
- See Laravel Support Policy: https://laravel.com/docs/master/releases#support-policy
- See Supported Versions of PHP: https://www.php.net/supported-versions.php
> Drop Support for Laravel 5.6, 5.7 and PHP 7.1

- src/Classifier.php
- src/Classifiers/Nova/DashboardClassifier.php
- test-stubs-nova/Dashboard.php
- tests/Stubs/Nova/DemoDashboard.php
Building upon the work done in #158. Unlike Actions, Filters and Lenses, Nova Dashboards have the FQDN of `Laravel\Nova\Dashboard` and not `Laravel\Nova\Dashboards\Dashboard`
Closes #154.
> Fix: FQDN/Namespace for Nova DashboardClassifier

- src/Classifiers/MiddlewareClassifier.php
- tests/ClassesFinderTest.php
- tests/Classifiers/MiddlewareClassifierTest.php
- tests/Console/StatsListCommandTest.php
- tests/Stubs/HttpKernel.php
- tests/Stubs/Middleware/DemoMiddleware.php
- tests/Stubs/Middleware/RouteMiddleware.php
The plural of "Middleware" is not "Middlewares". It's just "Middleware".
> Fix Plural Name of Middleware

- src/Classifier.php
- src/Classifiers/EventListenerClassifier.php
- src/Classifiers/ObserverClassifier.php
- tests/Classifiers/ObserverClassifierTest.php
- tests/Stubs/Models/User.php
- tests/Stubs/Observers/UserObserver.php
This PR adds the last (?) remaining Classifier to `stats`: [Observers](https://laravel.com/docs/master/eloquent#observers).
The Classifier works very similar to the EventListener Classifier. We resolve the Events-Dispatcher from the Laravel application, get all registered listeners, filter through the events and only keep the `eloquent.*` ones and finally check, if the registered class matches with the class which should be classified.
Closes #128
> Add Observer Classifier

- src/Classifiers/PolicyClassifier.php
- src/ValueObjects/ClassifiedClass.php
- src/ValueObjects/Component.php
- tests/Console/StatsListCommandTest.php
- tests/Stubs/Controllers/UsersController.php
- tests/ValueObjects/ClassifiedClassTest.php
- tests/ValueObjects/ComponentTest.php
This PR adds 2 new methods to a `ClassifiedClass` and to `Component`:
- `getNumberOfPublicMethods()`
- `getNumberOfNonPublicMethods()`
The methods are currently not in use. 
I plan to add them "somehow" to the statistics ASCII table.
Would also be cool to add them to the shared metrics in #178. I think adding a metric to show the distribution between public and non-public methods in controllers could be insightful.
> Add Counts for Public and Non Public Methods for Classified Classes and Components

- README.md
- src/Classifier.php
- src/Classifiers/DatabaseFactoryClassifier.php
- tests/Classifiers/DatabaseFactoryClassifierTest.php
- tests/ShareableMetrics/AllMetricPayloadKeysTest.php
- tests/Stubs/DatabaseFactories/StubUserDatabaseFactory.php
Adds support for the new Database Factories coming in Laravel 8: https://laravel.com/docs/8.x/database-testing#writing-factories
Closes #181
> Add Database Factory Classifier

- .github/workflows/tests.yml
- composer.json
- src/Classifiers/DatabaseFactoryClassifier.php
- tests/ClassesFinderTest.php
- tests/Classifiers/DatabaseFactoryClassifierTest.php
- tests/Stubs/DatabaseFactories/StubUserDatabaseFactory.php
This PR updates version constraints to support Laravel 8 which will be release on September 8th 2020.
I will give my best to tag a stable release of laravel-stats as soon as possible. However, the package depends on quite a lot of packages which all need to support Laravel 8 too. 
A stable release might be delayed by a couple of hours or days!
> Add Laravel 8 Support

- composer.json
Update the `stefanzweifel/laravel-stats-phploc` depdendency to a new major version. 
`stefanzweifel/laravel-stats-phploc` is a fork of [`sebastianbergmann/phploc`](https://github.com/sebastianbergmann/phploc). It recently has been updates with the latest changes from the original repository.
This closes #184.
> Upgrade stefanzweifel/laravel-stats-phploc to ^7.1

- .github/workflows/tests.yml
- composer.json
This PR updates the package to run on PHP 8.
The build currently fails, as `laravel/dusk` is not yet compatible with PHP 8. Dusk in turn is waiting on [`php-webdriver`](https://github.com/php-webdriver/php-webdriver/) to be updated to work with PHP 8. (https://github.com/laravel/dusk/pull/833)
I've also removed `friendsofphp/php-cs-fixer` as a dependency. (See https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4702#issuecomment-719545818)
> Add Support for PHP 8.0

- src/ShareableMetrics/ProjectName.php
This PR updates `ProjectName` to parse the correct project name from both SSH and HTTPS git remote connections.
For example:
```shell
https://github.com/stefanzweifel/laravel-stats.git #https
git@github.com:stefanzweifel/laravel-stats.git #ssh
```
> Add Support for SSH and HTTPS Connections

- composer.json
Continuation of #187
PHP CS Fixer v2.18 supports PHP v8
> Restore PHP CS Fixer

- composer.json
- rector.php
- src/ClassesFinder.php
- src/Classifier.php
- src/Classifiers/ResourceClassifier.php
- src/Contracts/Classifier.php
- src/Contracts/RejectionStrategy.php
- src/Outputs/AsciiTableOutput.php
- src/Outputs/JsonOutput.php
- src/ReflectionClass.php
- src/ShareableMetrics/Metrics/ComposerPsr4Sources.php
- src/ShareableMetrics/ProjectName.php
- src/ValueObjects/ClassifiedClass.php
This PR adds[`rector`](https://github.com/rectorphp/rector) to laravel-stats.
Through `rector` we can automatically upgrade the code base to use new PHP features.
> Add rector/rector to automatically refactor code in the future

- src/Classifiers/ObserverClassifier.php
- tests/ShareableMetrics/Metrics/CodeTestRatioTest.php
- tests/ShareableMetrics/Metrics/ProjectLinesOfCodeTest.php
- tests/ShareableMetrics/Metrics/ProjectLogicalLinesOfCodeTest.php
- tests/Stubs/Models/User.php
Fixes #192 by checking that the registered event listeners of type string. 
Event listeners which are registered as closures in a Models boot method are discarded.
> Fix: Make ObserverClassifier work with Closure Based Event Listeners

- config/stats.php
Closes #195 by excluding the Swoole Namespace.
> Exclude Swoole Namespace from being included by Stats by default

- .github/workflows/tests.yml
- composer.json
This PR drops support for Laravel 6 which will stop receiving bug fixes in January 2022. ([Laravel's support policy](https://laravel.com/docs/8.x/releases#support-policy)).
laravel-stats can still be installed in Laravel 6 projects. It will just not receive any new features that might be coming in the future.
This will make adding support for PHP 8.1 easier, as the builds for Larvel 6 on PHP 8.1 are failing (see #198)
> Drop Support for Laravel 6

- .github/workflows/tests.yml
- composer.json
- phpunit.xml
This PR updates the package to use my own fork of [phploc](https://github.com/stefanzweifel/phploc) so that we can support Laravel 10 and PHPUnit 10.
Fixes #214.
> Switch to forked phploc package and add support for Laravel 10 / PHPUnit 10

- .github/workflows/tests.yml
- .gitignore
- README.md
- composer.json
- src/ClassesFinder.php
- stubs/Pest.php
- stubs/PestTest.php
- stubs/README.md
- tests/ClassesFinderTest.php
This PR is an attempt to solve compatibility issues when the laravel-stats package is run in a project that uses [PestPHP](https://pestphp.com).
Due to the nature of how laravel-stats currently works, we can't easily provide support for Pest Tests. (`stats` searches for PHP **Classes** in your project and groups them into Components. Pest Tests are PHP files containing functions.)
This PR attempts to solve the compatibility issue, by checking the contents of a PHP file, before requiring it.
If the file contains "test" or "Test" and uses one of the prominent Pest PHP methods like `test()`, `it()`, `describe()` or `beforeEach()`, we consider it a Pest PHP file and exclude it from being required.
(Might be a too naive approach, but I can't think of anything better right now.)
When users run …
> Ignore Pest Files when finding and loading Classes

- src/Console/StatsListCommand.php
To reproduce bug.
Download a new install of Laravel. 
Install laravel-stats
php artisan stats
Error Message:
Not enough arguments (missing: "-c|--components=").
> Fix Laravel 10 bug in stats list command.

- src/ClassesFinder.php
> Sort Files when statistics is shown in Verbose Mode
